version: '0.0.1'
source: "https://github.com/tr7zw/ForgeFabricComposeTemplate/tree/1.19.2/"
replacements:
  group: "dev.tr7zw"
  name: "FirstPerson"
  id: "firstperson"
  version: "2.2.2"
  author: "tr7zw"
  relocationpackage: "dev.tr7zw.firstperson"
  dependencies: ""
  licensename: "LICENSE"
  curseforgeid: "333287"
  modrinthid: "H5XMjpHi"
rootProject:
  template: "."
subProjects:
  FPFabric:
    template: "Fabric"
    replacements:
      dependencies: "
      modCompileOnly 'maven.modrinth:playeranimator:0.4.0-test1-fabric'\n
      modCompileOnly 'maven.modrinth:freecam:1.1.6-mc1.19'\n
      "
  FPForge:
    template: "Forge"
    replacements:
      dependencies: '
      modImplementation "maven.modrinth:playeranimator:0.4.0-test1-forge"
      '