version: '0.0.1'
source: "https://github.com/tr7zw/ForgeFabricComposeTemplate/tree/1.18.2-shared/"
replacements:
  group: "dev.tr7zw"
  name: "FirstPerson"
  id: "firstperson"
  version: "2.1.2"
  author: "tr7zw"
  relocationpackage: "dev.tr7zw.firstperson"
  dependencies: ""
  licensename: "LICENSE"
rootProject:
  template: "."
subProjects:
  FPFabric:
    template: "Fabric"
    replacements:
      dependencies: '
      modImplementation "maven.modrinth:playeranimator:0.4.0-test1-fabric"
      '
  FPForge:
    template: "Forge"
    replacements:
      dependencies: '
      modImplementation "maven.modrinth:playeranimator:0.4.0-test1-forge"
      '