version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.18.2"
replacements:
  name: "FirstPerson"
  id: "firstperson"
  version: "2.2.3"
  relocationpackage: "dev.tr7zw.firstperson"
  curseforgeid: "333287"
  modrinthid: "H5XMjpHi"
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  FPFabric:
    template: "Fabric"
    replacements:
      dependencies: '
      modImplementation "maven.modrinth:playeranimator:0.4.0-test1+1.18-fabric"
      '
  FPForge:
    template: "Forge"
    replacements:
      dependencies: '
      modImplementation "maven.modrinth:playeranimator:0.4.0-test1+1.18-forge"
      '